input {
  beats {
    port => 5044
  }
}
filter {
  grok {
    match => {
      "message" => "%{MONTH:month}/%{MONTHDAY:day}-%{TIME:time} \[\*\*\] \[%{DATA:gid}:%{DATA:sid}:%{DATA:rev}\] %{DATA:alert_message} \[\*\*\] \[Priority: %{NUMBER:priority}\] \{%{DATA:protocol}\} %{IP:src_ip}:%{NUMBER:src_port} -> %{IP:dst_ip}:%{NUMBER:dst_port}"
    }
  }
}
output {
  elasticsearch {
    hosts => ["http://172.17.0.1:9200"]
    index => "snort-alerts-%{+YYYY.MM.dd}"
  }
}
